### ISSUE TITLE
Exporting EELS spectral maps

### ISSUE THREAD

**Issue by laenglem** [nion-software/nionswift-io#17]
I would like to export an Spectrum Image 128 x 128 x 512 and do some data analysis using Hypserspy. Is there an output format which can be read into hyperspy easily and correctly?

**Comment by laenglem** [comment]
never mind, I think I found the solution!

**Comment by cmeyer** [comment]
@laenglem Great. What was your solution? Is there any format we can export that would make it easier?

**Comment by laenglem** [comment]
I exported it as a dm3/dm4 file.
However what would be really convenient is if they could be exported directly as hyperspy format as this is a relatively practical way to analzye and plot EELS data
https://hyperspy.org/

**Comment by cmeyer** [comment]
Good idea. I opened a new issue.

- #19
